### ISSUE TITLE
Grunt Build Failing For SCSS Warning. 

### ISSUE THREAD

**Issue by ibrahim12** [imkevinxu/django-kevin#1]
I have just installed this template and when I am trying to start dev server with `foreman start`, it starts the server then crashed due to grunt build failure, screenshot below, 

![screen shot 2015-03-22 at 4 45 57 am](https://cloud.githubusercontent.com/assets/1056163/6767150/18d81154-d04d-11e4-9f50-f6c81e102378.png)

It has been fixed by fixing `glitch.scss` as bellow,

```
$white: #fff;
$yellow: #ff0;

.glitch {
  font-size: 80px;
  position: relative;

  &:after {
    animation: noise-anim 2s infinite linear alternate-reverse;
    clip: rect(0, 900px, 0, 0);
    content: attr(data-text);
    left: 2px;
    overflow: hidden;
    position: absolute;
    text-shadow: -1px 0 $white;
    top: 0;
  }

  &:before {
    animation: noise-anim-2 3s infinite linear alternate-reverse;
    clip: rect(0, 900px, 0, 0);
    content: attr(data-text);
    left: -2px;
    overflow: hidden;
    position: absolute;
    text-shadow: 1px 0 $yellow;
    top: 0;
  }
}

```

**Comment by imkevinxu** [comment]
Ah yes, the newest version of `grunt-scss-lint` seems to be more strict and checks for more rules. I've added a custom `.scss-lint.yml` to accommodate for some of these rules in the latest commit https://github.com/imkevinxu/django-kevin/commit/efc1ee8881d730d16c58be7d12387438ff8fd0c4
